import React, { useState } from 'react';
import { View, StyleSheet, ScrollView, Alert } from 'react-native';
import { TextInput, Button, Text, HelperText, IconButton, Divider } from 'react-native-paper';
import { useRouter } from 'expo-router';
import { useAuth } from '../../../contexts/AuthContext';
import { databaseService } from '../../../services/database';
import { ProgramItemInsert } from '../../../types';

interface ProgramItemForm {
  id: string;
  time: string;
  title: string;
  description: string;
  duration_minutes: string;
}

export default function CreateProgramScreen() {
  const [title, setTitle] = useState('');
  const [date, setDate] = useState('');
  const [items, setItems] = useState<ProgramItemForm[]>([
    { id: '1', time: '', title: '', description: '', duration_minutes: '' },
  ]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const router = useRouter();
  const { user } = useAuth();

  const addItem = () => {
    const newId = (Math.max(...items.map(i => parseInt(i.id))) + 1).toString();
    setItems([
      ...items,
      { id: newId, time: '', title: '', description: '', duration_minutes: '' },
    ]);
  };

  const removeItem = (id: string) => {
    if (items.length > 1) {
      setItems(items.filter(item => item.id !== id));
    }
  };

  const updateItem = (id: string, field: keyof ProgramItemForm, value: string) => {
    setItems(items.map(item =>
      item.id === id ? { ...item, [field]: value } : item
    ));
  };

  const validateForm = (): boolean => {
    if (!title.trim()) {
      setError('Please enter a program title');
      return false;
    }

    if (!date) {
      setError('Please enter a program date (YYYY-MM-DD)');
      return false;
    }

    // Validate date format
    const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
    if (!dateRegex.test(date)) {
      setError('Date must be in format YYYY-MM-DD');
      return false;
    }

    // Validate items
    for (let i = 0; i < items.length; i++) {
      const item = items[i];

      if (!item.title.trim()) {
        setError(`Item ${i + 1}: Please enter a title`);
        return false;
      }

      if (!item.time) {
        setError(`Item ${i + 1}: Please enter a time (HH:MM)`);
        return false;
      }

      // Validate time format
      const timeRegex = /^([01]\d|2[0-3]):([0-5]\d)$/;
      if (!timeRegex.test(item.time)) {
        setError(`Item ${i + 1}: Time must be in format HH:MM (24-hour)`);
        return false;
      }

      if (!item.duration_minutes || parseInt(item.duration_minutes) <= 0) {
        setError(`Item ${i + 1}: Please enter a valid duration in minutes`);
        return false;
      }
    }

    return true;
  };

  const handleCreate = async () => {
    if (!validateForm()) return;

    if (!user) {
      setError('You must be logged in to create a program');
      return;
    }

    setLoading(true);
    setError('');

    try {
      // Create program (share_code and share_token will be auto-generated by database trigger)
      const program = await databaseService.createProgram({
        title: title.trim(),
        date,
        status: 'draft',
        created_by: user.id,
      });

      // Create program items
      const sortedItems = items.sort((a, b) => a.time.localeCompare(b.time));

      for (let i = 0; i < sortedItems.length; i++) {
        const item = sortedItems[i];
        const programItem: ProgramItemInsert = {
          program_id: program.id,
          time: item.time,
          title: item.title.trim(),
          description: item.description.trim() || null,
          duration_minutes: parseInt(item.duration_minutes),
          order: i,
        };

        await databaseService.createProgramItem(programItem);
      }

      Alert.alert(
        'Success',
        'Program created successfully!',
        [
          {
            text: 'View Share Link',
            onPress: () => router.replace(`/(admin)/programs/${program.id}/share`),
          },
          {
            text: 'View Program',
            onPress: () => router.replace(`/(admin)/dashboard`),
          },
        ]
      );
    } catch (err: any) {
      setError(err.message || 'Failed to create program');
    } finally {
      setLoading(false);
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <View style={styles.header}>
        <Text variant="headlineMedium" style={styles.title}>
          Create Program
        </Text>
        <Text variant="bodyMedium" style={styles.subtitle}>
          Set up a new program flow for volunteers
        </Text>
      </View>

      <View style={styles.section}>
        <Text variant="titleMedium" style={styles.sectionTitle}>
          Program Details
        </Text>

        <TextInput
          label="Program Title *"
          value={title}
          onChangeText={setTitle}
          mode="outlined"
          style={styles.input}
          placeholder="e.g., Sunday Morning Service"
          disabled={loading}
        />

        <TextInput
          label="Date (YYYY-MM-DD) *"
          value={date}
          onChangeText={setDate}
          mode="outlined"
          style={styles.input}
          placeholder="2025-01-15"
          keyboardType="numbers-and-punctuation"
          disabled={loading}
        />
      </View>

      <Divider style={styles.divider} />

      <View style={styles.section}>
        <View style={styles.sectionHeader}>
          <Text variant="titleMedium" style={styles.sectionTitle}>
            Program Items
          </Text>
          <Button
            mode="outlined"
            onPress={addItem}
            icon="plus"
            compact
            disabled={loading}
          >
            Add Item
          </Button>
        </View>

        {items.map((item, index) => (
          <View key={item.id} style={styles.itemCard}>
            <View style={styles.itemHeader}>
              <Text variant="labelLarge">Item {index + 1}</Text>
              {items.length > 1 && (
                <IconButton
                  icon="close"
                  size={20}
                  onPress={() => removeItem(item.id)}
                  disabled={loading}
                />
              )}
            </View>

            <TextInput
              label="Time (HH:MM) *"
              value={item.time}
              onChangeText={(value) => updateItem(item.id, 'time', value)}
              mode="outlined"
              style={styles.input}
              placeholder="09:30"
              keyboardType="numbers-and-punctuation"
              disabled={loading}
            />

            <TextInput
              label="Title *"
              value={item.title}
              onChangeText={(value) => updateItem(item.id, 'title', value)}
              mode="outlined"
              style={styles.input}
              placeholder="e.g., Praise and Worship"
              disabled={loading}
            />

            <TextInput
              label="Description (Optional)"
              value={item.description}
              onChangeText={(value) => updateItem(item.id, 'description', value)}
              mode="outlined"
              style={styles.input}
              placeholder="Additional details..."
              multiline
              numberOfLines={2}
              disabled={loading}
            />

            <TextInput
              label="Duration (minutes) *"
              value={item.duration_minutes}
              onChangeText={(value) => updateItem(item.id, 'duration_minutes', value)}
              mode="outlined"
              style={styles.input}
              placeholder="30"
              keyboardType="number-pad"
              disabled={loading}
            />
          </View>
        ))}
      </View>

      {error ? (
        <HelperText type="error" visible={!!error} style={styles.error}>
          {error}
        </HelperText>
      ) : null}

      <View style={styles.actions}>
        <Button
          mode="contained"
          onPress={handleCreate}
          loading={loading}
          disabled={loading}
          style={styles.createButton}
          contentStyle={styles.buttonContent}
        >
          Create Program
        </Button>

        <Button
          mode="text"
          onPress={() => router.back()}
          disabled={loading}
        >
          Cancel
        </Button>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 24,
  },
  title: {
    fontWeight: 'bold',
    marginBottom: 8,
  },
  subtitle: {
    opacity: 0.7,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontWeight: '600',
    marginBottom: 16,
  },
  input: {
    marginBottom: 12,
  },
  divider: {
    marginVertical: 24,
  },
  itemCard: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  error: {
    marginBottom: 16,
  },
  actions: {
    marginTop: 24,
  },
  createButton: {
    marginBottom: 12,
  },
  buttonContent: {
    paddingVertical: 8,
  },
});
